### ISSUE TITLE
Unsupported db type: arangodb with cube:latest (0.30.39)

### ISSUE THREAD

**Issue by tokarenko** [panoti/cubejs-arangodb-driver#1]
ghcr.io/panoti/cube:main seems to be inoperable with the latest (0.30.39) Cube version.

```
Error while loading DB schema
Error: Unsupported db type: arangodb
at Object.driverDependencies (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:24:9)
at Object.lookupDriverClass (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:36:5)
at Function.createDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:50:23)
at CubejsServerCore.resolveDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:750:28)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at CubejsServerCore.getDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:723:22)
at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:108:22
at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9
```

I would be grateful if you could help to resolve the issue.

**Comment by panoti** [comment]
Could you provide to me your column type @tokarenko ? because I cannot support all data types 😅

**Comment by tokarenko** [comment]
@panoti, thank you for the feedback and the driver!

In the meantime I resolved the issue. The root cause is that the driver doesn't pass [isDriver()](https://github.com/cube-js/cube/blob/c167002de9e4dfdf4b57f1e384fb56306504b47a/packages/cubejs-server-core/src/core/DriverResolvers.ts#L47) check/. I suggest to change the driver class definition to inherit from the BaseDriver as in [PostgresDriver](https://github.com/cube-js/cube/blob/b2b9653854e5d0df10aabbcbdf5ab5af57f5d29c/packages/cubejs-postgres-driver/src/PostgresDriver.ts#L75)

The driver works with the following initialization code in cube.js:

```
const arango_db_driver = require("arangodb-cubejs-driver/dist/arangodb-driver.js").ArangoDbDriver;
const base_driver = require("@cubejs-backend/query-orchestrator").BaseDriver;

module.exports = {
  dbType: () => {
    return process.env.CUBEJS_DB_TYPE;
  },

  driverFactory: () => {

    // Workaround for the absence of inheritance from BaseDriver
    Object.setPrototypeOf(arango_db_driver.prototype,base_driver.prototype)

    return new arango_db_driver({
      url: process.env.CUBEJS_DB_URL,
      databaseName: process.env.CUBEJS_DB_NAME,
      auth: {
        username: process.env.CUBEJS_DB_USER,
        password: process.env.CUBEJS_DB_PASS,
      },
    });
  },
};

```

**Comment by panoti** [comment]
Ah, I believe my driver is really outdated. I will update it soon.

**Comment by tokarenko** [comment]
Please wait for a PR from me today with further modifications to make the driver work with any filters from the Cube GUI and allow for dynamic parameters in  when calling the driver.

**Comment by tokarenko** [comment]
@panoti , please add me as a contributor because I am unable to create feature branch.

**Comment by panoti** [comment]
@tokarenko you can fork this repo, then create a PR. I think it will be easier than creating feature branch.

**Comment by panoti** [comment]
Thanks @tokarenko  so much, I've upgrade this driver by using `@cubejs-backend/base-driver` and your wonderful contributing. Let check `v0.1.0` for the new features.
